!!io.github.vveird.audiodatastore.server.AudioStorage$AudioStorageConfiguration
accessList: []
endPoints: [io.github.vveird.audiodatastore.server.rest]
interfaceAdress: localhost
keys: []
port: 3002
root: data
uriBase: as
version: '0.1'
